[versions]
jmulticard = "2.0"
bouncycastle = "1.86"

[libraries]
jmulticard-android = { module = "es.gob.afirma.jmulticard:jmulticard-android", version.ref = "jmulticard" }
jmulticard-core = { module = "es.gob.afirma.jmulticard:jmulticard", version.ref = "jmulticard" }
jmulticard-jse = { module = "es.gob.afirma.jmulticard:jmulticard-jse", version.ref = "jmulticard" }
bcprov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
bcpkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle" }
bcutil = { module = "org.bouncycastle:bcutil-jdk18on", version.ref = "bouncycastle" }
