// Derechos de autor (C) 2026 Alberto Avidad Fernández.
// Autoría: Alberto Avidad Fernández
// Licencia: EUPL 1.2 o posterior
// SPDX-License-Identifier: EUPL-1.2

package rest

import (
	_ "embed"
	"sort"
	"strings"
)

//go:embed console_index.html
var consoleIndexHTML string

// consoleIndexPage devuelve la consola web local ya traducida.
//
// El HTML vive en console_index.html y se incrusta con go:embed. Mantenerlo
// como fichero permite que editores, linters de HTML y revisiones de
// accesibilidad trabajen sobre el; era imposible cuando estaba como literal de
// casi 3.900 lineas dentro de esta misma funcion.
func consoleIndexPage(lang string, t func(string, ...any) string) string {
	t = wrapWebLocalizer(lang, t)
	return translateConsoleIndexPage(consoleIndexHTML, lang, t)
}

func translateConsoleIndexPage(html string, lang string, t func(string, ...any) string) string {
	if strings.TrimSpace(lang) == "" {
		lang = "es"
	}
	replacements := []string{
		"__LANG_SELECTOR__", languageSelectorHTML("/", lang, t),
		"__LANG__", escapeHTMLAttr(lang),
		`<html lang="es">`, `<html lang="` + escapeHTMLAttr(lang) + `">`,
		"GrxFirma REST local", t("GrxFirma REST local"),
		"Consola web local para firma, verificación, certificados, ajustes y diagnóstico, sobre la API REST del propio backend.", t("Consola web local para firma, verificación, certificados, ajustes y diagnóstico, sobre la API REST del propio backend."),
		"Firmador Web", t("Firmador web"),
		"Validación avanzada", t("Validación avanzada"),
		"Health", t("Estado"),
		"Cargando consola...", t("Cargando consola..."),
		"Consola web lista.", t("Consola web lista."),
		"Estado", t("Estado"),
		"Actualizar estado", t("Actualizar estado"),
		"Estado del servicio", t("Estado del servicio"),
		"Autenticación", t("Autenticación"),
		"Bearer token", t("Bearer token"),
		"Requerido salvo autenticación por certificado. Se envía como Bearer.", t("Requerido salvo autenticación por certificado. Se envía como Bearer."),
		"La consola usa este token para endpoints protegidos como firma, verificación, ajustes o diagnóstico.", t("La consola usa este token para endpoints protegidos como firma, verificación, ajustes o diagnóstico."),
		"Accesos directos", t("Accesos directos"),
		"API base:", t("API base:"),
		"Entorno:", t("Entorno:"),
		"loopback local del equipo", t("loopback local del equipo"),
		"Descarga directa:", t("Descarga directa:"),
		"si la firma devuelve contenido base64, la consola genera un enlace de descarga.", t("si la firma devuelve contenido base64, la consola genera un enlace de descarga."),
		"Certificados", t("Certificados"),
		"Certificado seleccionado", t("Certificado seleccionado"),
		"Selecciona un certificado para exportar su resumen visible como JSON.", t("Selecciona un certificado para exportar su resumen visible como JSON."),
		"Copiar JSON del certificado", t("Copiar JSON del certificado"),
		"Copiar huella", t("Copiar huella"),
		"certificado", t("certificado"),
		"El certificado seleccionado no es apto para firma.", t("El certificado seleccionado no es apto para firma."),
		"El certificado seleccionado está caducado o expirado.", t("El certificado seleccionado está caducado o expirado."),
		"El certificado seleccionado está listo para firmar.", t("El certificado seleccionado está listo para firmar."),
		"Cargar certificados", t("Cargar certificados"),
		"Revisar certificados", t("Revisar certificados"),
		"Seleccionar automáticamente", t("Seleccionar automáticamente"),
		"Recordar certificado seleccionado", t("Recordar certificado seleccionado"),
		"La selección actual no se recordará entre sesiones.", t("La selección actual no se recordará entre sesiones."),
		"Activa la preferencia y selecciona un certificado para reutilizarlo en la siguiente sesión.", t("Activa la preferencia y selecciona un certificado para reutilizarlo en la siguiente sesión."),
		"La preferencia guardada ya no está disponible en el catálogo actual.", t("La preferencia guardada ya no está disponible en el catálogo actual."),
		"Certificado restaurado desde la sesión anterior: ", t("Certificado restaurado desde la sesión anterior: "),
		"Se reutilizará en la próxima sesión: ", t("Se reutilizará en la próxima sesión: "),
		"Filtro por asunto", t("Filtro por asunto"),
		"CN=..., NIF=..., etc.", t("CN=..., NIF=..., etc."),
		"Filtro por emisor", t("Filtro por emisor"),
		"FNMT, ACCV, ...", t("FNMT, ACCV, ..."),
		"Solo no caducados", t("Solo no caducados"),
		"Mostrando ", t("Mostrando "),
		" de ", t(" de "),
		" certificado(s).", t(" certificado(s)."),
		"Resumen del almacén", t("Resumen del almacén"),
		"Aptos para firma", t("Aptos para firma"),
		"Caducados", t("Caducados"),
		"Visibles", t("Visibles"),
		"Ningún certificado coincide con los filtros actuales.", t("Ningún certificado coincide con los filtros actuales."),
		"El certificado seleccionado actual queda fuera de los filtros.", t("El certificado seleccionado actual queda fuera de los filtros."),
		"La selección actual queda fuera de los filtros, pero se mantiene como referencia.", t("La selección actual queda fuera de los filtros, pero se mantiene como referencia."),
		"La selección actual es coherente con los filtros.", t("La selección actual es coherente con los filtros."),
		"La selección actual es coherente con los filtros visibles.", t("La selección actual es coherente con los filtros visibles."),
		"No hay certificados aptos para firma.", t("No hay certificados aptos para firma."),
		"Hay certificados aptos, pero ninguno queda visible con los filtros actuales.", t("Hay certificados aptos, pero ninguno queda visible con los filtros actuales."),
		"Hay certificados aptos para firma visibles.", t("Hay certificados aptos para firma visibles."),
		"No hay certificados visibles con caducidad próxima.", t("No hay certificados visibles con caducidad próxima."),
		"Hay certificados visibles que caducan en los próximos 30 días: ", t("Hay certificados visibles que caducan en los próximos 30 días: "),
		"Seleccionar", t("Seleccionar"),
		"Asunto", t("Asunto"),
		"Emisor", t("Emisor"),
		"Validez", t("Validez"),
		"Id", t("Id"),
		"Firmar", t("Firmar"),
		"Archivo a firmar", t("Archivo a firmar"),
		"Archivo(s) a firmar", t("Archivo(s) a firmar"),
		"o carpeta", t("o carpeta"),
		"o ruta local", t("o ruta local"),
		"/ruta/al/documento.pdf", t("/ruta/al/documento.pdf"),
		"Formato", t("Formato"),
		"Acción", t("Acción"),
		"Cofirma", t("Cofirma"),
		"Contrafirma", t("Contrafirma"),
		"Ruta de salida", t("Ruta de salida"),
		"/ruta/de/salida/opcional", t("/ruta/de/salida/opcional"),
		"Opciones JSON", t("Opciones JSON"),
		`{"strictCompat":"true","allowInvalidPDF":"false"}`, `{"strictCompat":"true","allowInvalidPDF":"false"}`,
		"Perfil de firma", t("Perfil de firma"),
		"Plan de firma listo.", t("Plan de firma listo."),
		"Pendiente de origen para firmar.", t("Pendiente de origen para firmar."),
		"Plan de firma", t("Plan de firma"),
		"Salida prevista", t("Salida prevista"),
		"Entrega", t("Entrega"),
		"Avanzado", t("Avanzado"),
		"Sobrescritura", t("Sobrescritura"),
		"Sin opciones avanzadas visibles.", t("Sin opciones avanzadas visibles."),
		"Sin perfil/TSA/subfiltro visibles.", t("Sin perfil/TSA/subfiltro visibles."),
		"Sin política/rol/lugar FacturaE visibles.", t("Sin política/rol/lugar FacturaE visibles."),
		"permitida", t("permitida"),
		"desactivada", t("desactivada"),
		"Lote: ", t("Lote: "),
		" fichero(s)", t(" fichero(s)"),
		"Fichero: ", t("Fichero: "),
		"Ruta local: ", t("Ruta local: "),
		"Pendiente de origen", t("Pendiente de origen"),
		"ruta automática si el backend la resuelve", t("ruta automática si el backend la resuelve"),
		"memoria", t("memoria"),
		"disco", t("disco"),
		"Baseline B", t("Baseline B"),
		"Baseline T", t("Baseline T"),
		"CAdES-LT", t("CAdES-LT"),
		"CAdES-LTA", t("CAdES-LTA"),
		"Aplica a PAdES, CAdES y XAdES. LT/LTA solo tiene efecto real en CAdES.", t("Aplica a PAdES, CAdES y XAdES. LT/LTA solo tiene efecto real en CAdES."),
		"URL TSA", t("URL TSA"),
		"https://tsa.ejemplo/", t("https://tsa.ejemplo/"),
		"Opcional. Si se indica, el backend la usará para perfiles con sello de tiempo.", t("Opcional. Si se indica, el backend la usará para perfiles con sello de tiempo."),
		"Subfiltro PAdES", t("Subfiltro PAdES"),
		"ETSI CAdES detached", t("ETSI CAdES detached"),
		"Adobe PKCS#7 detached", t("Adobe PKCS#7 detached"),
		"Solo aplica cuando el formato efectivo es PAdES.", t("Solo aplica cuando el formato efectivo es PAdES."),
		"FacturaE avanzada", t("FacturaE avanzada"),
		"Opcional. Este bloque expone política, rol y lugar de firma que el backend FacturaE ya consume de forma real.", t("Opcional. Este bloque expone política, rol y lugar de firma que el backend FacturaE ya consume de forma real."),
		"Política FacturaE", t("Política FacturaE"),
		"Rol FacturaE", t("Rol FacturaE"),
		"Identificador de política", t("Identificador de política"),
		"Hash de política", t("Hash de política"),
		"Qualifier de política", t("Qualifier de política"),
		"Ciudad", t("Ciudad"),
		"Provincia", t("Provincia"),
		"Código postal", t("Código postal"),
		"País", t("País"),
		"http://www.facturae.gob.es/politica_de_firma_formato_facturae/", t("http://www.facturae.gob.es/politica_de_firma_formato_facturae/"),
		"Ohixl6upD6av8N7pEvDABhEL6hM=", t("Ohixl6upD6av8N7pEvDABhEL6hM="),
		"https://www.facturae.gob.es/politica.html", t("https://www.facturae.gob.es/politica.html"),
		"emisor", t("emisor"),
		"18001", t("18001"),
		"ES", t("ES"),
		"Metadatos de la firma", t("Metadatos de la firma"),
		"Opcional. Estos datos se incrustan en la firma PAdES y no sustituyen al certificado ni al sello visible.", t("Opcional. Estos datos se incrustan en la firma PAdES y no sustituyen al certificado ni al sello visible."),
		"Motivo", t("Motivo"),
		"Ubicación", t("Ubicación"),
		"Contacto", t("Contacto"),
		"Firma electrónica avanzada", t("Firma electrónica avanzada"),
		"Granada", t("Granada"),
		"correo@ejemplo.es", t("correo@ejemplo.es"),
		"Activar sello visible (PAdES)", t("Activar sello visible (PAdES)"),
		"Atajo visual para configurar el sello sin salir de esta consola. Para previsualización avanzada sigue disponible ", t("Atajo visual para configurar el sello sin salir de esta consola. Para previsualización avanzada sigue disponible "),
		"Posición", t("Posición"),
		"Página", t("Página"),
		"Página(s)", t("Página(s)"),
		"Inferior izquierda", t("Inferior izquierda"),
		"Inferior derecha", t("Inferior derecha"),
		"Superior izquierda", t("Superior izquierda"),
		"Superior derecha", t("Superior derecha"),
		"Personalizada", t("Personalizada"),
		"Todas las páginas", t("Todas las páginas"),
		"X (0..1)", t("X (0..1)"),
		"Y (0..1)", t("Y (0..1)"),
		"Ancho (0..1)", t("Ancho (0..1)"),
		"Alto (0..1)", t("Alto (0..1)"),
		"Imagen de firma (opcional)", t("Imagen de firma (opcional)"),
		"Mantener texto visible del sello", t("Mantener texto visible del sello"),
		"QR del sello", t("QR del sello"),
		"https://verifica.ejemplo/", t("https://verifica.ejemplo/"),
		"Opcional. Si indicas un texto o URL, se incrusta un QR dentro del sello visible y puede combinarse con imagen personalizada.", t("Opcional. Si indicas un texto o URL, se incrusta un QR dentro del sello visible y puede combinarse con imagen personalizada."),
		"Guardar en disco si se usa ruta", t("Guardar en disco si se usa ruta"),
		"Devolver contenido firmado en base64", t("Devolver contenido firmado en base64"),
		"Sobrescribir salida", t("Sobrescribir salida"),
		"Procesando firma...", t("Procesando firma..."),
		"Selecciona un archivo o indica una ruta local.", t("Selecciona un archivo o indica una ruta local."),
		"Selecciona primero un certificado.", t("Selecciona primero un certificado."),
		"Firma completada correctamente.", t("Firma completada correctamente."),
		"Algoritmo", t("Algoritmo"),
		"Certificado", t("Certificado"),
		"Salida", t("Salida"),
		"en memoria", t("en memoria"),
		"Descargar firmado", t("Descargar firmado"),
		"Fichero", t("Fichero"),
		"Seleccionados", t("Seleccionados"),
		"Total", t("Total"),
		"OK", t("OK"),
		"KO", t("KO"),
		"ok", t("ok"),
		"error", t("error"),
		"Firma múltiple completada con incidencias (", t("Firma múltiple completada con incidencias ("),
		" correctos).", t(" correctos)."),
		"Firma múltiple completada (", t("Firma múltiple completada ("),
		" fichero(s)).", t(" fichero(s))."),
		"Firma múltiple finalizada.", t("Firma múltiple finalizada."),
		"Documento firmado.", t("Documento firmado."),
		"Error en firma: ", t("Error en firma: "),
		"Certificado seleccionado: ", t("Certificado seleccionado: "),
		"Backend REST operativo.", t("Backend REST operativo."),
		"Error consultando el estado: ", t("Error consultando el estado: "),
		"Estado del servicio consultado.", t("Estado del servicio consultado."),
		"Certificados cargados: ", t("Certificados cargados: "),
		"No se pudieron cargar los certificados: ", t("No se pudieron cargar los certificados: "),
		"Certificado seleccionado automáticamente: ", t("Certificado seleccionado automáticamente: "),
		"No hay certificado seleccionado.", t("No hay certificado seleccionado."),
		"Validez", t("Validez"),
		"Firma", t("Firma"),
		"Huella", t("Huella"),
		"Total", t("Total"),
		"apto para firma", t("apto para firma"),
		"no apto para firma", t("no apto para firma"),
		"No se pudo seleccionar certificado: ", t("No se pudo seleccionar certificado: "),
		"El JSON de opciones debe ser un objeto.", t("El JSON de opciones debe ser un objeto."),
		"Selección de páginas inválida. Usa 1, 1,3-5 o all.", t("Selección de páginas inválida. Usa 1, 1,3-5 o all."),
		"Verificar", t("Verificar"),
		"Archivo firmado", t("Archivo firmado"),
		"/ruta/al/documento_firmado.pdf", t("/ruta/al/documento_firmado.pdf"),
		"Original opcional", t("Original opcional"),
		"/ruta/al/original.pdf", t("/ruta/al/original.pdf"),
		"o ruta del original", t("o ruta del original"),
		"Sin documento original de referencia.", t("Sin documento original de referencia."),
		"Original de referencia aportado.", t("Original de referencia aportado."),
		"Tipo probable del original: ", t("Tipo probable del original: "),
		"PDF original", t("PDF original"),
		"XML original", t("XML original"),
		"ODF original", t("ODF original"),
		"OOXML original", t("OOXML original"),
		"Pendiente de pareja de validación.", t("Pendiente de pareja de validación."),
		"Validación prevista sin original de referencia.", t("Validación prevista sin original de referencia."),
		"Pareja de validación PDF/original detectada.", t("Pareja de validación PDF/original detectada."),
		"Pareja de validación XML/original detectada.", t("Pareja de validación XML/original detectada."),
		"Validación con original de referencia aportado.", t("Validación con original de referencia aportado."),
		"Compatibilidad de validación no evaluable sin ambos artefactos.", t("Compatibilidad de validación no evaluable sin ambos artefactos."),
		"Firmado y original parecen compatibles para validación.", t("Firmado y original parecen compatibles para validación."),
		"El firmado y el original parecen de tipos distintos.", t("El firmado y el original parecen de tipos distintos."),
		"No se pudo determinar la compatibilidad exacta del par.", t("No se pudo determinar la compatibilidad exacta del par."),
		"Pendiente de firmado para estimar el stack.", t("Pendiente de firmado para estimar el stack."),
		"No se pudo estimar el stack de firma probable.", t("No se pudo estimar el stack de firma probable."),
		"Stack de firma probable: ", t("Stack de firma probable: "),
		"No se pudo inferir el tipo probable del firmado.", t("No se pudo inferir el tipo probable del firmado."),
		"Tipo probable del firmado: ", t("Tipo probable del firmado: "),
		"PAdES/PDF", t("PAdES/PDF"),
		"CAdES/CMS", t("CAdES/CMS"),
		"XAdES", t("XAdES"),
		"XMLdSig", t("XMLdSig"),
		"ASiC-XAdES", t("ASiC-XAdES"),
		"ODF firmado", t("ODF firmado"),
		"OOXML firmado", t("OOXML firmado"),
		"XML firmado", t("XML firmado"),
		"Plan de validación", t("Plan de validación"),
		"Documento firmado", t("Documento firmado"),
		"Original", t("Original"),
		"Modo", t("Modo"),
		"Archivo cargado", t("Archivo cargado"),
		"Ruta local", t("Ruta local"),
		"Ruta local: ", t("Ruta local: "),
		"/ruta/al/documento.pdf o /ruta/al/directorio", t("/ruta/al/documento.pdf o /ruta/al/directorio"),
		"Pendiente de documento firmado", t("Pendiente de documento firmado"),
		"Pendiente de origen", t("Pendiente de origen"),
		"Sin original", t("Sin original"),
		"Plan de validación listo con original de referencia.", t("Plan de validación listo con original de referencia."),
		"Plan de validación listo sin documento original.", t("Plan de validación listo sin documento original."),
		"solo documento firmado", t("solo documento firmado"),
		"con original de referencia", t("con original de referencia"),
		"Validar documento", t("Validar documento"),
		"Validando documento...", t("Validando documento..."),
		"Selecciona un documento firmado o indica una ruta local.", t("Selecciona un documento firmado o indica una ruta local."),
		"Firma válida.", t("Firma válida."),
		"Firma no válida.", t("Firma no válida."),
		"Verificación automática", t("Verificación automática"),
		"Resumen de seguridad: ", t("Resumen de seguridad: "),
		"Firma íntegra y confiable.", t("Firma íntegra y confiable."),
		"Firma íntegra, pero con advertencias de confianza o certificado.", t("Firma íntegra, pero con advertencias de confianza o certificado."),
		"Firma inválida o integridad no garantizada.", t("Firma inválida o integridad no garantizada."),
		"Firma no válida: ", t("Firma no válida: "),
		"Razón", t("Razón"),
		"Firmantes", t("Firmantes"),
		"Detalles", t("Detalles"),
		"Cobertura", t("Cobertura"),
		"Integridad", t("Integridad"),
		"Confianza", t("Confianza"),
		"Advertencias", t("Advertencias"),
		"Errores", t("Errores"),
		"Evidencias", t("Evidencias"),
		"Firmantes resumidos", t("Firmantes resumidos"),
		"Tipo: ", t("Tipo: "),
		"Válida", t("Válida"),
		"Inválida", t("Inválida"),
		"Con advertencias", t("Con advertencias"),
		"Desconocido", t("Desconocido"),
		"No disponible", t("No disponible"),
		"Validación finalizada.", t("Validación finalizada."),
		"Error en verificación: ", t("Error en verificación: "),
		"Calculando huella...", t("Calculando huella..."),
		"Indica una ruta local de directorio para generar el manifiesto.", t("Indica una ruta local de directorio para generar el manifiesto."),
		"Selecciona un fichero o indica una ruta local.", t("Selecciona un fichero o indica una ruta local."),
		"Descargar manifiesto", t("Descargar manifiesto"),
		"Manifiesto de huellas generado.", t("Manifiesto de huellas generado."),
		"Entradas", t("Entradas"),
		"Manifiesto hash de directorio generado.", t("Manifiesto hash de directorio generado."),
		"Descargar huella", t("Descargar huella"),
		"Huella generada correctamente.", t("Huella generada correctamente."),
		"Huella generada.", t("Huella generada."),
		"Error al generar huella: ", t("Error al generar huella: "),
		"Comprobando integridad...", t("Comprobando integridad..."),
		"Indica una ruta local de directorio para comprobar el manifiesto.", t("Indica una ruta local de directorio para comprobar el manifiesto."),
		"Selecciona un fichero de huella/manifiesto o indica su ruta.", t("Selecciona un fichero de huella/manifiesto o indica su ruta."),
		"Descargar informe", t("Descargar informe"),
		"Directorio íntegro.", t("Directorio íntegro."),
		"Directorio con diferencias respecto al manifiesto.", t("Directorio con diferencias respecto al manifiesto."),
		"Huella válida.", t("Huella válida."),
		"La huella no coincide con el fichero.", t("La huella no coincide con el fichero."),
		"Coinciden", t("Coinciden"),
		"No coinciden", t("No coinciden"),
		"Hash sin fichero", t("Hash sin fichero"),
		"Fichero sin hash", t("Fichero sin hash"),
		"Sin coincidencias registradas.", t("Sin coincidencias registradas."),
		"No hay ficheros con hash distinto.", t("No hay ficheros con hash distinto."),
		"No hay entradas huérfanas en el manifiesto.", t("No hay entradas huérfanas en el manifiesto."),
		"No hay ficheros nuevos fuera del manifiesto.", t("No hay ficheros nuevos fuera del manifiesto."),
		"Comprobación de directorio finalizada.", t("Comprobación de directorio finalizada."),
		"Comprobación de huella finalizada.", t("Comprobación de huella finalizada."),
		"Esperada", t("Esperada"),
		"Error al comprobar huella: ", t("Error al comprobar huella: "),
		"Lote completado con incidencias.", t("Lote completado con incidencias."),
		"Plan de huella", t("Plan de huella"),
		"Crear huella", t("Crear huella"),
		"Comprobar huella", t("Comprobar huella"),
		"Recursivo", t("Recursivo"),
		"Guardar en disco", t("Guardar en disco"),
		"Guardar informe", t("Guardar informe"),
		"Ruta del fichero de huella", t("Ruta del fichero de huella"),
		"Ruta del informe (.hashreport)", t("Ruta del informe (.hashreport)"),
		"Estado actual", t("Estado actual"),
		"/ruta/de/salida opcional", t("/ruta/de/salida/opcional"),
		"/ruta/de/salida.hashreport", t("/ruta/de/salida.hashreport"),
		"No se pudo inferir el artefacto esperado de huella.", t("No se pudo inferir el artefacto esperado de huella."),
		"Artefacto de huella esperado: ", t("Artefacto de huella esperado: "),
		"La ruta de salida no termina en ", t("La ruta de salida no termina en "),
		"La ruta de salida coincide con el artefacto esperado: ", t("La ruta de salida coincide con el artefacto esperado: "),
		"Algoritmo en auto-detección desde la huella o el manifiesto.", t("Algoritmo en auto-detección desde la huella o el manifiesto."),
		"Algoritmo forzado para la comprobación: ", t("Algoritmo forzado para la comprobación: "),
		"Origen", t("Origen"),
		"Salida prevista", t("Salida prevista"),
		"Huella o manifiesto", t("Huella o manifiesto"),
		"Informe", t("Informe"),
		"crear", t("crear"),
		"comprobar", t("comprobar"),
		"__GRXFIRMA_BOOLEAN_YES__", t("Sí"),
		"__GRXFIRMA_BOOLEAN_NO__", t("No"),
		"__GRXFIRMA_ERROR_LABEL__", t("Error"),
		"Directorio", t("Directorio"),
		"Misma ruta o nombre derivado", t("Misma ruta o nombre derivado"),
		"Solo en memoria", t("Solo en memoria"),
		"Plan de huella listo para manifiesto de directorio.", t("Plan de huella listo para manifiesto de directorio."),
		"Plan de huella listo para fichero.", t("Plan de huella listo para fichero."),
		"Pendiente de origen para crear huella.", t("Pendiente de origen para crear huella."),
		"Pendiente de huella o manifiesto", t("Pendiente de huella o manifiesto"),
		"Ruta pendiente de informe", t("Ruta pendiente de informe"),
		"Sin informe en disco", t("Sin informe en disco"),
		"No se pudo inferir el tipo del artefacto de huella.", t("No se pudo inferir el tipo del artefacto de huella."),
		"El artefacto de huella parece de ", t("El artefacto de huella parece de "),
		"directorio", t("directorio"),
		"fichero", t("fichero"),
		" y no coincide con el modo actual.", t(" y no coincide con el modo actual."),
		"El artefacto de huella coincide con el modo seleccionado.", t("El artefacto de huella coincide con el modo seleccionado."),
		"Ruta pendiente de informe", t("Ruta pendiente de informe"),
		"Sin informe en disco", t("Sin informe en disco"),
		"Plan de comprobación listo para manifiesto de directorio.", t("Plan de comprobación listo para manifiesto de directorio."),
		"Plan de comprobación listo para fichero.", t("Plan de comprobación listo para fichero."),
		"Pendiente de origen o huella para comprobar.", t("Pendiente de origen o huella para comprobar."),
		"Proteger / Desproteger", t("Proteger / Desproteger"),
		"Cargar destinatarios", t("Cargar destinatarios"),
		"Exportar destinatario alto", t("Exportar destinatario alto"),
		"Importar destinatario alto", t("Importar destinatario alto"),
		"Fichero de destinatario fuerte", t("Fichero de destinatario fuerte"),
		"Destinatarios de protección", t("Destinatarios de protección"),
		"Perfil", t("Perfil"),
		"Contenedor", t("Contenedor"),
		"alto", t("alto"),
		"compat", t("compat"),
		"json (.afp)", t("json (.afp)"),
		"cms (.enveloped)", t("cms (.enveloped)"),
		"cms AuthEnvelopedData (.authenveloped.p7m)", t("cms AuthEnvelopedData (.authenveloped.p7m)"),
		"Destinatarios disponibles: ", t("Destinatarios disponibles: "),
		"No hay destinatarios seleccionados.", t("No hay destinatarios seleccionados."),
		"Hay un destinatario seleccionado.", t("Hay un destinatario seleccionado."),
		"Hay varios destinatarios seleccionados: ", t("Hay varios destinatarios seleccionados: "),
		"El perfil alto usa siempre contenedor json (.afp).", t("El perfil alto usa siempre contenedor json (.afp)."),
		"El perfil compat usará sobre CMS interoperable (.enveloped).", t("El perfil compat usará sobre CMS interoperable (.enveloped)."),
		"AuthEnvelopedData usa AES-256-GCM y RSA-OAEP-SHA256/MGF1-SHA256; requiere un destinatario compatible con certificado X.509 RSA válido.", t("AuthEnvelopedData usa AES-256-GCM y RSA-OAEP-SHA256/MGF1-SHA256; requiere un destinatario compatible con certificado X.509 RSA válido."),
		"El perfil compat usará contenedor json (.afp).", t("El perfil compat usará contenedor json (.afp)."),
		"Resumen del catálogo", t("Resumen del catálogo"),
		"No hay destinatarios locales válidos para cifrado.", t("No hay destinatarios locales válidos para cifrado."),
		"No hay destinatarios compatibles con el perfil seleccionado.", t("No hay destinatarios compatibles con el perfil seleccionado."),
		"Artefacto protegido esperado: ", t("Artefacto protegido esperado: "),
		"La ruta protegida no termina en ", t("La ruta protegida no termina en "),
		"La ruta protegida coincide con el artefacto esperado: ", t("La ruta protegida coincide con el artefacto esperado: "),
		"Origen", t("Origen"),
		"Contenedor efectivo", t("Contenedor efectivo"),
		"Salida prevista", t("Salida prevista"),
		"Entrega", t("Entrega"),
		"Plan de desprotección", t("Plan de desprotección"),
		"Plan de desprotección listo.", t("Plan de desprotección listo."),
		"Pendiente de origen para desproteger.", t("Pendiente de origen para desproteger."),
		"Pendiente de artefacto protegido.", t("Pendiente de artefacto protegido."),
		"No se pudo inferir el contenedor protegido por extensión.", t("No se pudo inferir el contenedor protegido por extensión."),
		"Contenedor protegido detectado: ", t("Contenedor protegido detectado: "),
		"json (.afp)", t("json (.afp)"),
		"cms (.enveloped)", t("cms (.enveloped)"),
		"cms/pkcs7 (.p7m)", t("cms/pkcs7 (.p7m)"),
		"Pendiente de origen", t("Pendiente de origen"),
		"activo", t("activo"),
		"automática ", t("automática "),
		"disco", t("disco"),
		"memoria", t("memoria"),
		" + base64", t(" + base64"),
		"Este destinatario fuerte usa contenedor json (.afp).", t("Este destinatario fuerte usa contenedor json (.afp)."),
		"Este destinatario compat usará sobre CMS interoperable.", t("Este destinatario compat usará sobre CMS interoperable."),
		"Este destinatario es compatible con AuthEnvelopedData autenticado.", t("Este destinatario es compatible con AuthEnvelopedData autenticado."),
		"Este destinatario compat usará contenedor json (.afp).", t("Este destinatario compat usará contenedor json (.afp)."),
		"Destinatarios seleccionados: ", t("Destinatarios seleccionados: "),
		"Destinatario seleccionado:", t("Destinatario seleccionado:"),
		"Destinatario de referencia:", t("Destinatario de referencia:"),
		"Fichero a proteger", t("Fichero a proteger"),
		"/ruta/al/documento.bin", t("/ruta/al/documento.bin"),
		"Ruta protegida", t("Ruta protegida"),
		"Ruta protegida", t("Ruta protegida"),
		"/ruta/de/salida/opcional.afp, .enveloped o .authenveloped.p7m", t("/ruta/de/salida/opcional.afp, .enveloped o .authenveloped.p7m"),
		"Guardar protegido en disco si se usa ruta", t("Guardar protegido en disco si se usa ruta"),
		"Devolver contenido protegido en base64", t("Devolver contenido protegido en base64"),
		"Proteger", t("Proteger"),
		"Protegiendo documento...", t("Protegiendo documento..."),
		"Selecciona un fichero para proteger o indica una ruta local.", t("Selecciona un fichero para proteger o indica una ruta local."),
		"Selecciona al menos un destinatario de protección.", t("Selecciona al menos un destinatario de protección."),
		"AuthEnvelopedData requiere destinatarios compatibles con certificado X.509 RSA válido.", t("AuthEnvelopedData requiere destinatarios compatibles con certificado X.509 RSA válido."),
		"Protección completada correctamente.", t("Protección completada correctamente."),
		"Destinatarios", t("Destinatarios"),
		"Descargar protegido", t("Descargar protegido"),
		"Documento protegido.", t("Documento protegido."),
		"Error en protección: ", t("Error en protección: "),
		"Destinatarios de protección cargados: ", t("Destinatarios de protección cargados: "),
		"No se pudieron cargar los destinatarios de protección: ", t("No se pudieron cargar los destinatarios de protección: "),
		"Selecciona exactamente un destinatario de protección.", t("Selecciona exactamente un destinatario de protección."),
		"No se pudo localizar el destinatario seleccionado.", t("No se pudo localizar el destinatario seleccionado."),
		"Exportando destinatario...", t("Exportando destinatario..."),
		"Solo se pueden exportar destinatarios del perfil alto.", t("Solo se pueden exportar destinatarios del perfil alto."),
		"Descargar destinatario", t("Descargar destinatario"),
		"Destinatario exportado.", t("Destinatario exportado."),
		"Destinatario fuerte exportado.", t("Destinatario fuerte exportado."),
		"Error en exportación de destinatario: ", t("Error en exportación de destinatario: "),
		"Importando destinatario...", t("Importando destinatario..."),
		"Selecciona un fichero de destinatario fuerte.", t("Selecciona un fichero de destinatario fuerte."),
		"Destinatario importado.", t("Destinatario importado."),
		"Destinatario fuerte importado.", t("Destinatario fuerte importado."),
		"Error en importación de destinatario: ", t("Error en importación de destinatario: "),
		"Descargar protegido", t("Descargar protegido"),
		"Descargar desprotegido", t("Descargar desprotegido"),
		"Fichero protegido", t("Fichero protegido"),
		"/ruta/al/documento.afp, .enveloped o .authenveloped.p7m", t("/ruta/al/documento.afp, .enveloped o .authenveloped.p7m"),
		"Ruta desprotegida", t("Ruta desprotegida"),
		"Ruta desprotegida", t("Ruta desprotegida"),
		"Guardar desprotegido en disco si se usa ruta", t("Guardar desprotegido en disco si se usa ruta"),
		"Devolver contenido desprotegido en base64", t("Devolver contenido desprotegido en base64"),
		"Desproteger", t("Desproteger"),
		"Desprotegiendo documento...", t("Desprotegiendo documento..."),
		"Selecciona un fichero protegido o indica una ruta local.", t("Selecciona un fichero protegido o indica una ruta local."),
		"Desprotección completada correctamente.", t("Desprotección completada correctamente."),
		"Destinatario", t("Destinatario"),
		"Documento", t("Documento"),
		"Descargar desprotegido", t("Descargar desprotegido"),
		"Documento desprotegido.", t("Documento desprotegido."),
		"Error en desprotección: ", t("Error en desprotección: "),
		"Importar P12/PFX", t("Importar P12/PFX"),
		"Archivo P12/PFX", t("Archivo P12/PFX"),
		"Contraseña", t("Contraseña"),
		"Importar certificado", t("Importar certificado"),
		"Importando certificado...", t("Importando certificado..."),
		"Selecciona un fichero P12 o PFX.", t("Selecciona un fichero P12 o PFX."),
		"Certificado importado.", t("Certificado importado."),
		"Error de importación.", t("Error de importación."),
		"Ajustes", t("Ajustes"),
		"Cargar ajustes", t("Cargar ajustes"),
		"Guardar ajustes", t("Guardar ajustes"),
		"JSON de ajustes", t("JSON de ajustes"),
		"Ajustes cargados.", t("Ajustes cargados."),
		"Ajustes guardados.", t("Ajustes guardados."),
		"Diagnóstico y TLS", t("Diagnóstico y TLS"),
		"Estado TLS", t("Estado TLS"),
		"Informe diagnóstico", t("Informe diagnóstico"),
		"Instalar confianza TLS local", t("Instalar confianza TLS local"),
		"Vaciar almacén TLS local", t("Vaciar almacén TLS local"),
		"Informe diagnóstico", t("Informe diagnóstico"),
		"Instalar confianza TLS local", t("Instalar confianza TLS local"),
		"Vaciar almacén TLS local", t("Vaciar almacén TLS local"),
		"Esto instalará o reinstalará la confianza TLS local en este equipo. ¿Continuar?", t("Esto instalará o reinstalará la confianza TLS local en este equipo. ¿Continuar?"),
		"Esto vaciará el almacén TLS local de GrxFirma y puede romper la consola web segura hasta reinstalar la confianza. ¿Continuar?", t("Esto vaciará el almacén TLS local de GrxFirma y puede romper la consola web segura hasta reinstalar la confianza. ¿Continuar?"),
		"Certificado TLS local generado. Revisa o reinstala la confianza si el navegador sigue advirtiendo.", t("Certificado TLS local generado. Revisa o reinstala la confianza si el navegador sigue advirtiendo."),
		"Certificado TLS local no generado. La consola segura puede no funcionar hasta generarlo e instalar su confianza.", t("Certificado TLS local no generado. La consola segura puede no funcionar hasta generarlo e instalar su confianza."),
		"Estado certificado", t("Estado certificado"),
		"Confianza del sistema", t("Confianza del sistema"),
		"dependiente de la plataforma", t("dependiente de la plataforma"),
		"Backend", t("Backend"),
		"Disponible", t("Disponible"),
		"Plataforma", t("Plataforma"),
		"Motivo", t("Motivo"),
		"Artefactos TLS", t("Artefactos TLS"),
		"Certificado local", t("Certificado local"),
		"Claves privadas", t("Claves privadas"),
		"generado", t("generado"),
		"no generado", t("no generado"),
		"Sin incidencias", t("Sin incidencias"),
		"Sin proxy", t("Sin proxy"),
		"Proxy del sistema", t("Proxy del sistema"),
		"Proxy configurado", t("Proxy configurado"),
		"Proxy autenticado", t("Proxy autenticado"),
		"Modo de proxy en ejecución", t("Modo de proxy en ejecución"),
		"El almacén seguro de secretos de proxy está disponible para este backend local.", t("El almacén seguro de secretos de proxy está disponible para este backend local."),
		"El almacén seguro de secretos de proxy no está listo; el proxy autenticado puede quedar limitado en este equipo.", t("El almacén seguro de secretos de proxy no está listo; el proxy autenticado puede quedar limitado en este equipo."),
		"Error al consultar estado TLS: ", t("Error al consultar estado TLS: "),
		"Estado del almacén seguro de proxy consultado.", t("Estado del almacén seguro de proxy consultado."),
		"Error al consultar el almacén seguro de proxy: ", t("Error al consultar el almacén seguro de proxy: "),
		"Diagnóstico local correcto: hay certificados utilizables para firmar.", t("Diagnóstico local correcto: hay certificados utilizables para firmar."),
		"Diagnóstico local con advertencias: no se detectan certificados utilizables para firmar.", t("Diagnóstico local con advertencias: no se detectan certificados utilizables para firmar."),
		"Certificados detectados", t("Certificados detectados"),
		"Certificados utilizables", t("Certificados utilizables"),
		"Artefactos TLS locales", t("Artefactos TLS locales"),
		"Directorio TLS local", t("Directorio TLS local"),
		"Error al generar diagnóstico: ", t("Error al generar diagnóstico: "),
		"Abrir OpenAPI", t("Abrir OpenAPI"),
		"Ejecutando...", t("Ejecutando..."),
		"Estado TLS consultado.", t("Estado TLS consultado."),
		"Diagnóstico generado.", t("Diagnóstico generado."),
		"Copiar diagnóstico", t("Copiar diagnóstico"),
		"JSON del certificado copiado al portapapeles.", t("JSON del certificado copiado al portapapeles."),
		"No se pudo copiar el JSON del certificado.", t("No se pudo copiar el JSON del certificado."),
		"Huella del certificado copiada al portapapeles.", t("Huella del certificado copiada al portapapeles."),
		"No se pudo copiar la huella del certificado.", t("No se pudo copiar la huella del certificado."),
		"Resultado de instalación de confianza TLS local.", t("Resultado de instalación de confianza TLS local."),
		"Almacén TLS local vaciado.", t("Almacén TLS local vaciado."),
		"Esta consola usa los endpoints REST ya existentes del backend local de GrxFirma. Si un endpoint requiere autenticación, introduce el token Bearer arriba.", t("Esta consola usa los endpoints REST ya existentes del backend local de GrxFirma. Si un endpoint requiere autenticación, introduce el token Bearer arriba."),
	}
	type replacementPair struct {
		old string
		new string
	}
	pairs := make([]replacementPair, 0, len(replacements)/2)
	for i := 0; i+1 < len(replacements); i += 2 {
		pairs = append(pairs, replacementPair{old: replacements[i], new: replacements[i+1]})
	}
	sort.SliceStable(pairs, func(i, j int) bool {
		return len(pairs[i].old) > len(pairs[j].old)
	})
	ordered := make([]string, 0, len(replacements))
	for _, pair := range pairs {
		ordered = append(ordered, pair.old, pair.new)
	}
	return strings.NewReplacer(ordered...).Replace(html)
}

func escapeHTMLAttr(v string) string {
	return strings.NewReplacer("&", "&amp;", "\"", "&quot;", "<", "&lt;", ">", "&gt;").Replace(v)
}
