#!/usr/bin/env python3
# Derechos de autor (C) 2026 Alberto Avidad Fernández.
# Autoría: Alberto Avidad Fernández
# Licencia: EUPL 1.2 o posterior
# SPDX-License-Identifier: EUPL-1.2

"""Harden a project generated by safari-web-extension-converter.

The converter deliberately emits a placeholder native handler. This script
replaces that placeholder and the macOS container view controller, then wires
shared Keychain entitlements into every Debug/Release build configuration.
"""

from __future__ import annotations

import argparse
import json
import os
import plistlib
import re
import stat
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Optional
from urllib.parse import urlsplit


MARKER = "GRXFIRMA_SAFARI_BRIDGE_V1"
HANDLER_TEMPLATE = "SafariWebExtensionHandler.swift.in"
APP_TEMPLATE = "ViewController.swift.in"
NATIVE_ONLY_TEMPLATE = "SafariNativeOnly.js.in"
NATIVE_ONLY_START = "// GRXFIRMA_SAFARI_NATIVE_ONLY_START"
NATIVE_ONLY_END = "// GRXFIRMA_SAFARI_NATIVE_ONLY_END"


class PostprocessError(RuntimeError):
    pass


@dataclass(frozen=True)
class GeneratedLayout:
    project: Path
    handler: Path
    view_controller: Path
    background: Path
    extension_bundle_id: str
    app_target_id: str
    app_target_name: str
    extension_target_id: str
    extension_target_name: str
    app_configuration_ids: frozenset[str]
    extension_configuration_ids: frozenset[str]


@dataclass(frozen=True)
class OriginalFile:
    existed: bool
    data: bytes
    mode: int


def parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Instala el puente nativo seguro en un proyecto Safari generado"
    )
    parser.add_argument("--project-dir", required=True, type=Path)
    parser.add_argument("--bundle-id", required=True)
    parser.add_argument("--default-endpoint", default="https://127.0.0.1:63118")
    parser.add_argument(
        "--template-dir", type=Path, default=Path(__file__).resolve().parent
    )
    return parser.parse_args(argv)


def validate_bundle_id(value: str) -> str:
    value = value.strip()
    if not re.fullmatch(r"[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)+", value):
        raise PostprocessError(f"bundle identifier no valido: {value!r}")
    return value


def validate_endpoint(value: str) -> str:
    value = value.strip().rstrip("/")
    parsed = urlsplit(value)
    try:
        port = parsed.port
    except ValueError as exc:
        raise PostprocessError(
            "el endpoint Safari debe ser HTTPS loopback en el puerto 63118"
        ) from exc
    if (
        parsed.scheme != "https"
        or parsed.hostname not in {"127.0.0.1", "::1"}
        or port != 63118
        or parsed.username is not None
        or parsed.password is not None
        or parsed.query
        or parsed.fragment
        or parsed.path not in {"", "/"}
    ):
        raise PostprocessError(
            "el endpoint Safari debe ser HTTPS loopback en el puerto 63118"
        )
    return value


def find_single(root: Path, pattern: str, label: str) -> Path:
    matches = sorted(path for path in root.rglob(pattern) if path.is_file())
    if len(matches) != 1:
        raise PostprocessError(
            f"se esperaba un unico {label}; encontrados {len(matches)} en {root}"
        )
    if matches[0].is_symlink():
        raise PostprocessError(f"no se admite un enlace simbolico para {label}")
    return matches[0]


def pbx_section(pbx_text: str, name: str) -> str:
    start_marker = f"/* Begin {name} section */"
    end_marker = f"/* End {name} section */"
    start = pbx_text.find(start_marker)
    end = pbx_text.find(end_marker)
    if start < 0 or end < 0 or end <= start:
        raise PostprocessError(f"project.pbxproj no contiene la seccion {name}")
    return pbx_text[start + len(start_marker) : end]


def pbx_objects(section: str) -> dict[str, str]:
    objects: dict[str, str] = {}
    current_id: Optional[str] = None
    current_lines: list[str] = []
    depth = 0
    for line in section.splitlines(keepends=True):
        if current_id is None:
            match = re.match(r"^\s*([A-Za-z0-9]+)(?:\s*/\*.*?\*/)?\s*=\s*\{\s*$", line)
            if not match:
                continue
            current_id = match.group(1)
            current_lines = [line]
            depth = line.count("{") - line.count("}")
            continue
        current_lines.append(line)
        depth += line.count("{") - line.count("}")
        if depth == 0:
            if current_id in objects:
                raise PostprocessError(
                    f"identificador PBX duplicado en project.pbxproj: {current_id}"
                )
            objects[current_id] = "".join(current_lines)
            current_id = None
            current_lines = []
    if current_id is not None:
        raise PostprocessError("objeto PBX sin cerrar en project.pbxproj")
    return objects


def pbx_scalar(body: str, key: str) -> Optional[str]:
    match = re.search(rf"^\s*{re.escape(key)}\s*=\s*(.+?);\s*$", body, re.MULTILINE)
    if not match:
        return None
    value = match.group(1).strip()
    if value.startswith('"') and value.endswith('"'):
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as exc:
            raise PostprocessError(f"valor PBX no valido para {key}") from exc
        if isinstance(decoded, str):
            return decoded
    return value


def pbx_configuration_ids(body: str) -> tuple[str, ...]:
    match = re.search(r"buildConfigurations\s*=\s*\((.*?)\);", body, re.DOTALL)
    if not match:
        raise PostprocessError("target Xcode sin lista de configuraciones")
    identifiers = tuple(
        re.findall(
            r"^\s*([A-Za-z0-9]+)(?:\s*/\*.*?\*/)?\s*,\s*$", match.group(1), re.MULTILINE
        )
    )
    if not identifiers:
        raise PostprocessError("target Xcode sin configuraciones de build")
    return identifiers


def discover_targets(
    pbx_text: str, bundle_id: str
) -> tuple[dict[str, object], dict[str, object]]:
    targets = pbx_objects(pbx_section(pbx_text, "PBXNativeTarget"))
    configuration_lists = pbx_objects(pbx_section(pbx_text, "XCConfigurationList"))
    configurations = pbx_objects(pbx_section(pbx_text, "XCBuildConfiguration"))
    discovered: list[dict[str, object]] = []
    for target_id, body in targets.items():
        product_type = pbx_scalar(body, "productType")
        if product_type not in {
            "com.apple.product-type.application",
            "com.apple.product-type.app-extension",
        }:
            continue
        configuration_list_id = pbx_scalar(body, "buildConfigurationList")
        if configuration_list_id is None:
            raise PostprocessError("target Xcode sin buildConfigurationList")
        configuration_list_id = configuration_list_id.split()[0]
        try:
            configuration_ids = pbx_configuration_ids(
                configuration_lists[configuration_list_id]
            )
        except KeyError as exc:
            raise PostprocessError(
                "buildConfigurationList de target no encontrada"
            ) from exc
        names: set[str] = set()
        bundle_ids: set[str] = set()
        for configuration_id in configuration_ids:
            try:
                configuration = configurations[configuration_id]
            except KeyError as exc:
                raise PostprocessError(
                    f"configuracion Xcode no encontrada: {configuration_id}"
                ) from exc
            name = pbx_scalar(configuration, "name")
            configured_bundle_id = pbx_scalar(
                configuration, "PRODUCT_BUNDLE_IDENTIFIER"
            )
            if name is None or configured_bundle_id is None:
                raise PostprocessError(
                    "configuracion de target sin nombre o PRODUCT_BUNDLE_IDENTIFIER"
                )
            names.add(name)
            bundle_ids.add(configured_bundle_id)
        if not {"Debug", "Release"}.issubset(names):
            raise PostprocessError(
                "los targets Safari deben incluir configuraciones Debug y Release"
            )
        if len(bundle_ids) != 1:
            raise PostprocessError("un target Safari usa varios Bundle IDs")
        discovered.append(
            {
                "id": target_id,
                "name": pbx_scalar(body, "name") or target_id,
                "product_type": product_type,
                "configuration_ids": frozenset(configuration_ids),
                "bundle_id": next(iter(bundle_ids)),
            }
        )

    apps = [
        target
        for target in discovered
        if target["product_type"] == "com.apple.product-type.application"
        and target["bundle_id"] == bundle_id
    ]
    extensions = [
        target
        for target in discovered
        if target["product_type"] == "com.apple.product-type.app-extension"
        and isinstance(target["bundle_id"], str)
        and target["bundle_id"].startswith(bundle_id + ".")
    ]
    if len(apps) != 1 or len(extensions) != 1:
        raise PostprocessError(
            "no se identificaron de forma univoca los targets app y Safari extension "
            f"(app={len(apps)}, extension={len(extensions)})"
        )
    return apps[0], extensions[0]


def discover_layout(project_dir: Path, bundle_id: str) -> GeneratedLayout:
    if not project_dir.is_dir():
        raise PostprocessError(f"no existe el directorio de proyecto: {project_dir}")

    project = find_single(project_dir, "project.pbxproj", "project.pbxproj")
    handler = find_single(
        project_dir,
        "SafariWebExtensionHandler.swift",
        "SafariWebExtensionHandler.swift",
    )
    background = find_single(project_dir, "background.js", "background.js")

    candidates = sorted(
        path for path in project_dir.rglob("ViewController.swift") if path.is_file()
    )
    if len(candidates) != 1:
        raise PostprocessError(
            "layout del conversor no reconocido: se esperaba un unico "
            f"ViewController.swift de macOS y se encontraron {len(candidates)}"
        )
    view_controller = candidates[0]
    if view_controller.is_symlink():
        raise PostprocessError(
            "no se admite un enlace simbolico para ViewController.swift"
        )

    pbx_text = project.read_text(encoding="utf-8")
    app_target, extension_target = discover_targets(pbx_text, bundle_id)

    return GeneratedLayout(
        project=project,
        handler=handler,
        view_controller=view_controller,
        background=background,
        extension_bundle_id=str(extension_target["bundle_id"]),
        app_target_id=str(app_target["id"]),
        app_target_name=str(app_target["name"]),
        extension_target_id=str(extension_target["id"]),
        extension_target_name=str(extension_target["name"]),
        app_configuration_ids=app_target["configuration_ids"],
        extension_configuration_ids=extension_target["configuration_ids"],
    )


def render_template(path: Path, replacements: dict[str, str]) -> str:
    if not path.is_file():
        raise PostprocessError(f"falta la plantilla: {path}")
    rendered = path.read_text(encoding="utf-8")
    for key, value in replacements.items():
        rendered = rendered.replace(f"__{key}__", value)
    leftovers = sorted(set(re.findall(r"__[A-Z0-9_]+__", rendered)))
    if leftovers:
        raise PostprocessError(
            f"marcadores sin resolver en {path.name}: {', '.join(leftovers)}"
        )
    if MARKER not in rendered:
        raise PostprocessError(f"la plantilla {path.name} no contiene {MARKER}")
    return rendered


def patch_background(source: str, shim: str) -> str:
    if NATIVE_ONLY_START not in shim or NATIVE_ONLY_END not in shim:
        raise PostprocessError(
            "la plantilla SafariNativeOnly.js.in no tiene marcadores"
        )
    start_count = source.count(NATIVE_ONLY_START)
    end_count = source.count(NATIVE_ONLY_END)
    if start_count != end_count or start_count > 1:
        raise PostprocessError(
            "marcadores Safari nativos inconsistentes en background.js"
        )
    if start_count == 1 and source.rstrip().endswith(shim.strip()):
        return source.rstrip() + "\n"
    if start_count == 1:
        start = source.index(NATIVE_ONLY_START)
        try:
            end = source.index(NATIVE_ONLY_END, start) + len(NATIVE_ONLY_END)
        except ValueError as exc:
            raise PostprocessError(
                "marcadores Safari nativos desordenados en background.js"
            ) from exc
        source = source[:start] + source[end:]
    return source.rstrip() + "\n\n" + shim.strip() + "\n"


def write_if_changed(path: Path, content: str) -> None:
    normalized = content.rstrip() + "\n"
    write_bytes_if_changed(path, normalized.encode("utf-8"))


def write_bytes_if_changed(path: Path, data: bytes) -> None:
    if path.is_symlink():
        raise PostprocessError(f"no se sobrescribe el enlace simbolico: {path}")
    if path.exists() and path.read_bytes() == data:
        return
    atomic_write(path, data)


def normalized_text_bytes(content: str) -> bytes:
    return (content.rstrip() + "\n").encode("utf-8")


def atomic_write(path: Path, data: bytes) -> None:
    if path.is_symlink():
        raise PostprocessError(f"no se sobrescribe el enlace simbolico: {path}")
    mode = stat.S_IMODE(path.stat().st_mode) if path.exists() else 0o644
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent, prefix=f".{path.name}.", suffix=".tmp"
    )
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as temporary_file:
            temporary_file.write(data)
            temporary_file.flush()
            os.fsync(temporary_file.fileno())
        temporary_path.chmod(mode)
        os.replace(temporary_path, path)
    finally:
        temporary_path.unlink(missing_ok=True)


def entitlements_bytes(access_group: str, network_client: bool) -> bytes:
    payload: dict[str, object] = {
        "com.apple.security.app-sandbox": True,
        "keychain-access-groups": [access_group],
    }
    if network_client:
        payload["com.apple.security.network.client"] = True
    return plistlib.dumps(payload, fmt=plistlib.FMT_XML, sort_keys=True)


def transactional_write(outputs: dict[Path, bytes], secure_directory: Path) -> None:
    if secure_directory.is_symlink():
        raise PostprocessError(
            "el directorio de auditoria no puede ser un enlace simbolico"
        )
    directory_existed = secure_directory.exists()
    if directory_existed and not secure_directory.is_dir():
        raise PostprocessError("la ruta de auditoria existe y no es un directorio")
    original_directory_mode = (
        stat.S_IMODE(secure_directory.stat().st_mode) if directory_existed else None
    )

    originals: dict[Path, OriginalFile] = {}
    for path in outputs:
        if path.is_symlink():
            raise PostprocessError(f"no se sobrescribe el enlace simbolico: {path}")
        if path.exists() and not path.is_file():
            raise PostprocessError(f"la salida existe y no es un fichero: {path}")
        if path.parent != secure_directory and not path.parent.is_dir():
            raise PostprocessError(f"no existe el directorio de salida: {path.parent}")
        originals[path] = OriginalFile(
            existed=path.exists(),
            data=path.read_bytes() if path.exists() else b"",
            mode=stat.S_IMODE(path.stat().st_mode) if path.exists() else 0o644,
        )

    try:
        secure_directory.mkdir(mode=0o700, exist_ok=True)
        secure_directory.chmod(0o700)
        for path, data in outputs.items():
            write_bytes_if_changed(path, data)
    except Exception as exc:
        rollback_errors: list[str] = []
        for path, original in reversed(list(originals.items())):
            try:
                if original.existed:
                    atomic_write(path, original.data)
                    path.chmod(original.mode)
                elif path.exists() or path.is_symlink():
                    path.unlink()
            except OSError as rollback_error:
                rollback_errors.append(f"{path}: {rollback_error}")
        try:
            if directory_existed and original_directory_mode is not None:
                secure_directory.chmod(original_directory_mode)
            elif secure_directory.exists():
                secure_directory.rmdir()
        except OSError as rollback_error:
            rollback_errors.append(f"{secure_directory}: {rollback_error}")
        if rollback_errors:
            raise PostprocessError(
                "fallo el postprocesado y tambien su rollback: "
                + "; ".join(rollback_errors)
            ) from exc
        raise


def relative_build_path(project_file: Path, target_file: Path) -> str:
    return target_file.relative_to(project_file.parent.parent).as_posix()


def patch_build_settings(
    pbx_text: str,
    bundle_id: str,
    extension_bundle_id: str,
    app_configuration_ids: frozenset[str],
    extension_configuration_ids: frozenset[str],
    app_entitlements: str,
    extension_entitlements: str,
) -> tuple[str, int, int]:
    lines = pbx_text.splitlines(keepends=True)
    output: list[str] = []
    app_count = 0
    extension_count = 0
    index = 0

    while index < len(lines):
        line = lines[index]
        if "buildSettings = {" not in line:
            output.append(line)
            index += 1
            continue

        configuration_id: Optional[str] = None
        for previous_line in reversed(output):
            configuration_match = re.match(
                r"^\s*([A-Za-z0-9]+)(?:\s*/\*.*?\*/)?\s*=\s*\{\s*$",
                previous_line,
            )
            if configuration_match:
                configuration_id = configuration_match.group(1)
                break
            if re.match(r"^\s*};\s*$", previous_line):
                break
        if configuration_id is None:
            raise PostprocessError(
                "no se pudo asociar buildSettings con su XCBuildConfiguration"
            )

        block = [line]
        index += 1
        while index < len(lines):
            block.append(lines[index])
            if re.match(r"^\s*};\s*$", lines[index]):
                index += 1
                break
            index += 1

        block_text = "".join(block)
        bundle_match = re.search(
            r"^\s*PRODUCT_BUNDLE_IDENTIFIER\s*=\s*([^;]+);",
            block_text,
            re.MULTILINE,
        )
        if not bundle_match:
            output.extend(block)
            continue

        configured_id = bundle_match.group(1).strip().strip('"')
        if configuration_id in app_configuration_ids:
            if configured_id != bundle_id:
                raise PostprocessError(
                    f"Bundle ID inesperado en configuracion app {configuration_id}"
                )
            entitlements = app_entitlements
            app_count += 1
        elif configuration_id in extension_configuration_ids:
            if configured_id != extension_bundle_id:
                raise PostprocessError(
                    f"Bundle ID inesperado en configuracion extension {configuration_id}"
                )
            entitlements = extension_entitlements
            extension_count += 1
        else:
            output.extend(block)
            continue

        filtered = [
            item
            for item in block
            if not re.match(
                r"^\s*(CODE_SIGN_ENTITLEMENTS|ENABLE_APP_SANDBOX|ENABLE_HARDENED_RUNTIME|ENABLE_OUTGOING_NETWORK_CONNECTIONS)\s*=",
                item,
            )
        ]
        product_index = next(
            pos
            for pos, item in enumerate(filtered)
            if "PRODUCT_BUNDLE_IDENTIFIER" in item
        )
        indent = re.match(r"^(\s*)", filtered[product_index]).group(1)
        additions = [
            f'{indent}CODE_SIGN_ENTITLEMENTS = "{entitlements}";\n',
            f"{indent}ENABLE_APP_SANDBOX = YES;\n",
            f"{indent}ENABLE_HARDENED_RUNTIME = YES;\n",
        ]
        if configured_id == extension_bundle_id:
            additions.append(f"{indent}ENABLE_OUTGOING_NETWORK_CONNECTIONS = YES;\n")
        filtered[product_index:product_index] = additions
        output.extend(filtered)

    if app_count != len(app_configuration_ids) or extension_count != len(
        extension_configuration_ids
    ):
        raise PostprocessError(
            "no se localizaron todas las configuraciones de ambos targets "
            f"(app={app_count}/{len(app_configuration_ids)}, "
            f"extension={extension_count}/{len(extension_configuration_ids)})"
        )
    return "".join(output), app_count, extension_count


def postprocess(
    project_dir: Path, template_dir: Path, bundle_id: str, default_endpoint: str
) -> dict[str, object]:
    bundle_id = validate_bundle_id(bundle_id)
    default_endpoint = validate_endpoint(default_endpoint)
    if project_dir.is_symlink() or template_dir.is_symlink():
        raise PostprocessError(
            "project-dir y template-dir no pueden ser enlaces simbolicos"
        )
    project_dir = project_dir.resolve()
    template_dir = template_dir.resolve()
    layout = discover_layout(project_dir, bundle_id)

    service = bundle_id + ".bridge-configuration"
    access_group = "$(AppIdentifierPrefix)" + bundle_id + ".shared"
    replacements = {
        "DEFAULT_ENDPOINT": default_endpoint,
        "EXTENSION_BUNDLE_ID": layout.extension_bundle_id,
        "KEYCHAIN_ACCESS_GROUP_SUFFIX": bundle_id + ".shared",
        "KEYCHAIN_SERVICE": service,
    }

    handler_text = render_template(template_dir / HANDLER_TEMPLATE, replacements)
    app_text = render_template(template_dir / APP_TEMPLATE, replacements)
    native_only_template = template_dir / NATIVE_ONLY_TEMPLATE
    if not native_only_template.is_file():
        raise PostprocessError(f"falta la plantilla: {native_only_template}")
    background_text = patch_background(
        layout.background.read_text(encoding="utf-8"),
        native_only_template.read_text(encoding="utf-8"),
    )
    app_entitlements_file = (
        layout.view_controller.parent / "GrxFirmaApp.entitlements"
    )
    extension_entitlements_file = (
        layout.handler.parent / "GrxFirmaExtension.entitlements"
    )
    project_text = layout.project.read_text(encoding="utf-8")
    patched, app_configs, extension_configs = patch_build_settings(
        project_text,
        bundle_id,
        layout.extension_bundle_id,
        layout.app_configuration_ids,
        layout.extension_configuration_ids,
        relative_build_path(layout.project, app_entitlements_file),
        relative_build_path(layout.project, extension_entitlements_file),
    )

    audit_dir = project_dir / ".grxfirma-safari"
    report = {
        "schema": 1,
        "marker": MARKER,
        "bundle_id": bundle_id,
        "extension_bundle_id": layout.extension_bundle_id,
        "app_target": {
            "id": layout.app_target_id,
            "name": layout.app_target_name,
            "configuration_ids": sorted(layout.app_configuration_ids),
        },
        "extension_target": {
            "id": layout.extension_target_id,
            "name": layout.extension_target_name,
            "configuration_ids": sorted(layout.extension_configuration_ids),
        },
        "default_endpoint": default_endpoint,
        "keychain_service": service,
        "handler": str(layout.handler.relative_to(project_dir)),
        "view_controller": str(layout.view_controller.relative_to(project_dir)),
        "background": str(layout.background.relative_to(project_dir)),
        "project": str(layout.project.relative_to(project_dir)),
        "app_entitlements": str(app_entitlements_file.relative_to(project_dir)),
        "extension_entitlements": str(
            extension_entitlements_file.relative_to(project_dir)
        ),
        "app_build_configurations": app_configs,
        "extension_build_configurations": extension_configs,
    }
    report_path = audit_dir / "integration-report.json"
    outputs = {
        layout.handler: normalized_text_bytes(handler_text),
        layout.view_controller: normalized_text_bytes(app_text),
        layout.background: normalized_text_bytes(background_text),
        app_entitlements_file: entitlements_bytes(access_group, network_client=False),
        extension_entitlements_file: entitlements_bytes(
            access_group, network_client=True
        ),
        layout.project: normalized_text_bytes(patched),
        audit_dir / HANDLER_TEMPLATE: (template_dir / HANDLER_TEMPLATE).read_bytes(),
        audit_dir / APP_TEMPLATE: (template_dir / APP_TEMPLATE).read_bytes(),
        audit_dir / NATIVE_ONLY_TEMPLATE: native_only_template.read_bytes(),
        report_path: normalized_text_bytes(
            json.dumps(report, indent=2, sort_keys=True)
        ),
    }
    transactional_write(outputs, audit_dir)
    return report


def main(argv: Optional[list[str]] = None) -> int:
    args = parse_args(argv)
    try:
        report = postprocess(
            args.project_dir,
            args.template_dir,
            args.bundle_id,
            args.default_endpoint,
        )
    except (OSError, ValueError, PostprocessError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
